name: Incash
version: 1.0
api-version: "1.13"
website: "https://incash.gg/"
main: gg.incash.bukkit.BukkitIncashPlugin
description: "Incash integration for Bukkit servers"
author: Incash

commands:
  incash:
    description: "Reload Incash config"
    usage: "/incash reload"
    permission: incash.reload
    permission-message: ""

permissions:
  incash.reload:
    default: "op"