# Change it with your own risk
apiUri: "http://localhost:8081/server-gateway"

# Replace it with your shop id, that you can find at Server - Main
shopId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# Replace it with your server id, that you can find at Server - Servers - Server ID
serverId: "xXxXXxXxXXxXxx"

# Change to true if you need advanced log
debug: true